# name:etl pipline
on:
   push:
     branches:
        -main

jobs :
  extract-data-job: 
      runs-on: ubuntu-latest
      
      steps:
        - name: checkout code
          uses: action/checkout@v2

        - name: setup python
          uses: action/setup-python@v6
          with:
            python-version:'3.10'

        - name: install required dependencies 
          run: pip install -r .github/workflow/requirments.txt

        - name: run extract.py
          run: python .github/workflow/extract.py


  transform-data-job:
      runs-on: ubuntu-latest
      need: extract-data-job

      steps:
        - name: checkout code
          uses: action/checkout@v2

        - name: run transform.py
          run:  python .github/workflow/transform.py

  load-data-jobs:
      runs-on: ubuntu-latest
      need: transform-data-job

      steps:
         - name: checkout code
           uses: action/checkout@v2

         - name: run load.py
           run: python .github/workflow/load.py 



            
